apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-maintenance
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: human-connection
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    human-connection.org/selector: deployment-maintenance
