apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-neo4j
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: human-connection
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: web
    port: 7474
    targetPort: 7474
  selector:
    human-connection.org/selector: deployment-neo4j
